version: '3.9'
services:
  app:
    build: 
      context: .
      dockerfile: dockerfile.node
    container_name: nodejs-app
    working_dir: /app 
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
